apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustom/sealed-secrets
    repoURL: git@github.com:Camphul/argocd-deployment-repo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
